### ISSUE TITLE
build (npm install) as is fails

### ISSUE THREAD

**Issue by shumiyao** [travis-r6s/gridsome-starter-shopify#20]
As a workaround, we now need to do:

```
npm install --legacy-peer-deps
```

Any plans to update `gridsome-starter-shopify`?

Currently clicking on "Install Now" in [this page](https://gridsome.org/starters/shopify-starter/) fails

**Comment by travis-r6s** [comment]
Hey @shumiyao 
Does it show a particular install error? And could I check what Node version you are using?

**Comment by shumiyao** [comment]
@thetre97 

Thank you for a response. I am using node v15.12.0. It was a fresh cloned repo with clean install.

I could observe the same with the `Deploy to Netlify` button accessible in [this page](https://gridsome.org/starters/shopify-starter/)

Please try:

https://app.netlify.com/start/deploy?repository=https://github.com/thetre97/gridsome-starter-shopify

<details>
<summary>Click to toggle contents of `LOG`</summary>

```
6:42:36 PM: Build ready to start
6:42:38 PM: build-image version: be42e453d6c8f171cc2f654acc29c0a8b60e6d93
6:42:38 PM: build-image tag: v3.7.1
6:42:38 PM: buildbot version: d27947bc03aca4728afa0eb80795ace23b863de1
6:42:38 PM: Fetching cached dependencies
6:42:38 PM: Failed to fetch cache, continuing with build
6:42:38 PM: Starting to prepare the repo for build
6:42:38 PM: No cached dependencies found. Cloning fresh repo
6:42:38 PM: git clone https://github.com/thetre97/gridsome-starter-shopify
6:42:39 PM: Preparing Git Reference refs/heads/main
6:42:41 PM: Starting build script
6:42:41 PM: Installing dependencies
6:42:41 PM: Python version set to 2.7
6:42:42 PM: v12.18.0 is already installed.
6:42:42 PM: Now using node v12.18.0 (npm v6.14.4)
6:42:42 PM: Started restoring cached build plugins
6:42:42 PM: Finished restoring cached build plugins
6:42:43 PM: Attempting ruby version 2.7.1, read from environment
6:42:44 PM: Using ruby version 2.7.1
6:42:44 PM: Using PHP version 5.6
6:42:44 PM: Started restoring cached yarn cache
6:42:44 PM: Finished restoring cached yarn cache
6:42:44 PM: Installing yarn at version 1.22.4
6:42:44 PM: Installing Yarn!
6:42:44 PM: > Downloading tarball...
6:42:44 PM: [1/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz --> /tmp/yarn.tar.gz.gvJU222ZGC
6:42:44 PM:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
6:42:44 PM:                                  Dload  Upload   Total   Spent    Left  Speed
6:42:44 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
6:42:44 PM: 100    79  100    79    0     0    317      0 --:--:-- --:--:-- --:--:--   318
6:42:45 PM:   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
6:42:45 PM: 100    93  100    93    0     0    182      0 --:--:-- --:--:-- --:--:--   364
6:42:45 PM: 100   625  100   625    0     0    688      0 --:--:-- --:--:-- --:--:--   688
6:42:45 PM:  60 1215k   60  732k    0     0   584k      0  0:00:02  0:00:01  0:00:01  584k
6:42:45 PM: 100 1215k  100 1215k    0     0   932k      0  0:00:01  0:00:01 --:--:-- 9667k
6:42:45 PM: [2/2]: https://yarnpkg.com/downloads/1.22.4/yarn-v1.22.4.tar.gz.asc --> /tmp/yarn.tar.gz.gvJU222ZGC.asc
6:42:46 PM: 100    83  100    83    0     0   1627      0 --:--:-- --:--:-- --:--:--  1627
6:42:46 PM: 100    97  100    97    0     0   1220      0 --:--:-- --:--:-- --:--:--  1220
6:42:46 PM: 100   629  100   629    0     0   2805      0 --:--:-- --:--:-- --:--:--  2805
6:42:46 PM: 100  1028  100  1028    0     0   3649      0 --:--:-- --:--:-- --:--:--  3649
6:42:46 PM: > Verifying integrity...
6:42:46 PM: gpg: Signature made Mon 09 Mar 2020 03:52:13 PM UTC using RSA key ID 69475BAA
6:42:46 PM: gpg: Good signature from "Yarn Packaging <yarn@dan.cx>"
6:42:46 PM: gpg: WARNING: This key is not certified with a trusted signature!
6:42:46 PM: gpg:          There is no indication that the signature belongs to the owner.
6:42:46 PM: Primary key fingerprint: 72EC F46A 56B4 AD39 C907  BBB7 1646 B01B 86E5 0310
6:42:46 PM:      Subkey fingerprint: 6D98 490C 6F1A CDDD 448E  4595 4F77 6793 6947 5BAA
6:42:46 PM: > GPG signature looks good
6:42:46 PM: > Extracting to ~/.yarn...
6:42:46 PM: > Adding to $PATH...
6:42:46 PM: > Successfully installed Yarn 1.22.4! Please open another terminal where the `yarn` command will now be available.
6:42:46 PM: Started restoring cached node modules
6:42:46 PM: Finished restoring cached node modules
6:42:47 PM: Installing NPM modules using Yarn version 1.22.4
6:42:47 PM: yarn install v1.22.4
6:42:47 PM: [1/4] Resolving packages...
6:42:48 PM: [2/4] Fetching packages...
6:42:49 PM: warning mini-css-extract-plugin@0.5.0: Invalid bin field for "mini-css-extract-plugin".
6:42:50 PM: warning url-loader@1.1.2: Invalid bin field for "url-loader".
6:43:06 PM: info fsevents@1.2.13: The platform "linux" is incompatible with this module.
6:43:06 PM: info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
6:43:06 PM: info fsevents@2.1.3: The platform "linux" is incompatible with this module.
6:43:06 PM: info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
6:43:06 PM: [3/4] Linking dependencies...
6:43:06 PM: warning " > apollo-boost@0.4.9" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > apollo-cache@1.3.5" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > apollo-cache-inmemory@1.6.6" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > apollo-client@2.6.10" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > apollo-link@1.2.14" has unmet peer dependency "graphql@^0.11.3 || ^0.12.3 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > apollo-link-http@1.5.17" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > graphql-tag@2.10.3" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0".
6:43:06 PM: warning "apollo-boost > apollo-cache > apollo-utilities@1.3.4" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning "apollo-boost > apollo-link-error > apollo-link-http-common@0.2.16" has unmet peer dependency "graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning " > graphql-tag@2.11.0" has unmet peer dependency "graphql@^0.9.0 || ^0.10.0 || ^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0".
6:43:06 PM: warning " > vue-apollo@3.0.5" has unmet peer dependency "apollo-client@^2.0.0".
6:43:06 PM: warning " > vue-apollo@3.0.5" has unmet peer dependency "apollo-link@^1.0.0".
6:43:06 PM: warning " > vue-notification@1.3.20" has unmet peer dependency "vue@^2.0.0".
6:43:06 PM: warning " > vuex@3.5.1" has unmet peer dependency "vue@^2.0.0".
6:43:06 PM: warning "eslint-config-travisreynolds-vue > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
6:43:06 PM: warning "eslint-config-travisreynolds-vue > eslint-plugin-vue-a11y@0.0.31" has incorrect peer dependency "eslint@^3 || ^4 || ^5".
6:43:06 PM: warning "eslint-config-travisreynolds-vue > eslint-plugin-vue-a11y > eslint-plugin-vue@5.2.3" has incorrect peer dependency "eslint@^5.0.0".
6:43:06 PM: warning "eslint-config-travisreynolds-vue > eslint-plugin-vue-a11y > vue-eslint-parser@6.0.5" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
6:43:06 PM: warning "eslint-config-travisreynolds-vue > eslint-plugin-vue-a11y > eslint-plugin-vue > vue-eslint-parser@5.0.0" has incorrect peer dependency "eslint@^5.0.0".
6:43:06 PM: warning " > sass-loader@10.0.4" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
6:43:14 PM: [4/4] Building fresh packages...
6:43:18 PM: Done in 31.25s.
6:43:18 PM: NPM modules installed using Yarn
6:43:18 PM: Started restoring cached go cache
6:43:18 PM: Finished restoring cached go cache
6:43:19 PM: go version go1.14.4 linux/amd64
6:43:19 PM: go version go1.14.4 linux/amd64
6:43:19 PM: Installing missing commands
6:43:19 PM: Verify run directory
6:43:20 PM: ​
6:43:20 PM: ────────────────────────────────────────────────────────────────
6:43:20 PM:   Netlify Build                                                 
6:43:20 PM: ────────────────────────────────────────────────────────────────
6:43:20 PM: ​
6:43:20 PM: ❯ Version
6:43:20 PM:   @netlify/build 11.2.4
6:43:20 PM: ​
6:43:20 PM: ❯ Flags
6:43:20 PM:   deployId: 6085aa0c4d5948118f5aca33
6:43:20 PM: ​
6:43:20 PM: ❯ Current directory
6:43:20 PM:   /opt/build/repo
6:43:20 PM: ​
6:43:20 PM: ❯ Config file
6:43:20 PM:   No config file was defined: using default values.
6:43:20 PM: ​
6:43:20 PM: ❯ Context
6:43:20 PM:   production
6:43:20 PM: ​
6:43:20 PM: ────────────────────────────────────────────────────────────────
6:43:20 PM:   1. Build command from Netlify app                             
6:43:20 PM: ────────────────────────────────────────────────────────────────
6:43:20 PM: ​
6:43:20 PM: $ yarn build
6:43:20 PM: yarn run v1.22.4
6:43:20 PM: $ gridsome build
6:43:21 PM: Gridsome v0.7.21
6:43:21 PM: Initializing plugins...
6:43:21 PM: Error: Missing store name or url.
6:43:21 PM:     at new ShopifySource (/opt/build/repo/node_modules/gridsome-source-shopify/lib/index.js:29:56)
6:43:21 PM:     at Plugins.initialize (/opt/build/repo/node_modules/gridsome/lib/app/Plugins.js:61:11)
6:43:21 PM:     at App.init (/opt/build/repo/node_modules/gridsome/lib/app/App.js:120:18)
6:43:21 PM:     at App.bootstrap (/opt/build/repo/node_modules/gridsome/lib/app/App.js:49:16)
6:43:21 PM:     at module.exports (/opt/build/repo/node_modules/gridsome/lib/app/index.js:12:18)
6:43:21 PM:     at module.exports (/opt/build/repo/node_modules/gridsome/lib/build.js:17:21)
6:43:21 PM:     at /opt/build/repo/node_modules/gridsome/index.js:44:12
6:43:21 PM:     at Command.<anonymous> (/opt/build/repo/node_modules/gridsome/index.js:20:42)
6:43:21 PM:     at Command.listener (/opt/build/repo/node_modules/commander/index.js:315:8)
6:43:21 PM:     at Command.emit (events.js:315:20)
6:43:21 PM:     at Command.parseArgs (/opt/build/repo/node_modules/commander/index.js:651:12)
6:43:21 PM:     at Command.parse (/opt/build/repo/node_modules/commander/index.js:474:21)
6:43:21 PM:     at Object.<anonymous> (/opt/build/repo/node_modules/@gridsome/cli/bin/gridsome.js:79:9)
6:43:21 PM:     at Module._compile (internal/modules/cjs/loader.js:1138:30)
6:43:21 PM:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
6:43:21 PM:     at Module.load (internal/modules/cjs/loader.js:986:32)
6:43:21 PM: error Command failed with exit code 1.
6:43:21 PM: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
6:43:21 PM: ​
6:43:21 PM: ────────────────────────────────────────────────────────────────
6:43:21 PM:   "build.command" failed                                        
6:43:21 PM: ────────────────────────────────────────────────────────────────
6:43:21 PM: ​
6:43:21 PM:   Error message
6:43:21 PM:   Command failed with exit code 1: yarn build
6:43:21 PM: ​
6:43:21 PM:   Error location
6:43:21 PM:   In Build command from Netlify app:
6:43:21 PM:   yarn build
6:43:21 PM: ​
6:43:21 PM:   Resolved config
6:43:21 PM:   build:
6:43:21 PM:     command: yarn build
6:43:21 PM:     commandOrigin: ui
6:43:21 PM:     publish: /opt/build/repo/dist
6:43:22 PM: Caching artifacts
6:43:22 PM: Started saving node modules
6:43:22 PM: Finished saving node modules
6:43:22 PM: Started saving build plugins
6:43:22 PM: Finished saving build plugins
6:43:22 PM: Started saving yarn cache
6:43:22 PM: Finished saving yarn cache
6:43:22 PM: Started saving pip cache
6:43:22 PM: Finished saving pip cache
6:43:22 PM: Started saving emacs cask dependencies
6:43:22 PM: Finished saving emacs cask dependencies
6:43:22 PM: Started saving maven dependencies
6:43:22 PM: Finished saving maven dependencies
6:43:22 PM: Started saving boot dependencies
6:43:22 PM: Finished saving boot dependencies
6:43:22 PM: Started saving rust rustup cache
6:43:22 PM: Finished saving rust rustup cache
6:43:22 PM: Started saving go dependencies
6:43:22 PM: Finished saving go dependencies
6:43:24 PM: Build failed due to a user error: Build script returned non-zero exit code: 2
6:43:24 PM: Creating deploy upload records
6:43:24 PM: Failing build: Failed to build site
6:43:24 PM: Failed during stage 'building site': Build script returned non-zero exit code: 2
6:43:24 PM: Finished processing build request in 46.488985656s
```
</details>

**Comment by travis-r6s** [comment]
Have you added the necessary environment variables? It seems to install okay from those logs, but is missing the Shopify store name - `Error: Missing store name or url.`

See: https://github.com/thetre97/gridsome-starter-shopify#developing

**Comment by shumiyao** [comment]
@thetre97 

oh, sorry I have missed that out, 

I am very sorry to bother you and thank you very much for taking time on this issue. Can I close this issue?

**Comment by travis-r6s** [comment]
No worries - sure, you can close it 👍
